services:
  # 1. Nosso Banco de Dados
  postgres_clima:
    image: postgres:15
    container_name: postgres_clima
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=clima_dw
    ports:
      - "5434:5432"
    volumes:
      - postgres_clima_data:/var/lib/postgresql/data

  # 2. O Novo Airflow
  airflow:
    image: apache/airflow:2.7.1-python3.10
    container_name: apache_airflow
    restart: always
    command: standalone
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
    env_file:
      - .env  # 🔥 ADICIONADO: Agora o Airflow lê suas chaves do arquivo .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # Instala as bibliotecas automaticamente ao subir o contêiner:
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas sqlalchemy psycopg2-binary requests google-generativeai pendulum
    ports:
      - "8080:8080"
    depends_on:
      - postgres_clima

volumes:
  postgres_clima_data: