name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install pandas sqlalchemy requests pendulum

      - name: Validar sintaxe dos scripts
        run: |
          python -m py_compile src/*.py
          python -m py_compile dags/*.py